### ISSUE TITLE
Check for X times

### ISSUE THREAD

**Issue by rei-paypay** [jsalinaspolo/logcapture#168]
Hello there,

First, a big thank you for the library, as it's proving very useful in our test cases.

As stated in the title, is it currently possible to check for the log messages X times, for example, when logging as part of a loop?

I'm going through the source code, but I have not found anything related to this.

Regards

**Comment by jsalinaspolo** [comment]
Thanks @rei-paypay 

I do not think there is a matcher in hamecrast for that, but let me think about a DSL to support that

I imagine you would like something like the following?

```
  def "verify n items"() {
    expect:
    log.info("a message")
    log.info("a message")

    logged(aLog().info().withMessage("a message")).times(2)
  }

```

**Comment by rei-paypay** [comment]
@jsalinaspolo 

Thanks for getting back.

Yes something like that would be great to have.

**Comment by jsalinaspolo** [comment]
Would something like this work for you?

```
  def "verify n times logs"() {
    expect:
    log.info("a message")
    log.info("a message")

    logged(aLog().info().withMessage("a message"), 2)
  }
```

https://github.com/jsalinaspolo/logcapture/pull/170

**Comment by rei-paypay** [comment]
@jsalinaspolo 
Hey sorry for the late reply.
Yes that looks perfectly okay.'
Thank you.

**Comment by rei-paypay** [comment]
I think we can close this one down for now :)

**Comment by jsalinaspolo** [comment]
It will be part of `1.3.1` version
https://github.com/jsalinaspolo/logcapture/pull/174

Thanks @rei-paypay
