### ISSUE TITLE
Boolean APIs

### ISSUE THREAD

**Issue by rei-paypay** [jsalinaspolo/logcapture#173]
@jsalinaspolo 
Not sure if this has been raised before, but is there away to have the same APIs but return a boolean instead?

So instead of
```
logged(aLog().info().withMessage("a message"))
```
maybe something like
```
isLogged(aLog().info().withMessage("a message")) == true
```

The reason is that this will give more flexibility to work with other frameworks like kotest where I can have a precondition like
```
until(10.seconds) {
    isLogged(aLog().info().withMessage("a message"))
}
```

Do let me know if this is something we can have or not.

Thanks.

**Comment by jsalinaspolo** [comment]
I never had to return `Booleans` as using Matchers have been easy to decouple from other frameworks.

It would not work with `kotest` the [eventually](https://kotest.io/docs/assertions/eventually.html) like this test 

```kotlin
  "use eventually to verify logs" {
    var i = 0
    eventually(1.seconds) {
      i += 1
      logMessageWhenCondition(log, i == 5)
      logCaptureListener.logged(aLog().info().withMessage("a message"))
    }
  }
```

https://github.com/jsalinaspolo/logcapture/blob/main/logcapture-kotest/src/test/kotlin/org/logcapture/kotest/LogCaptureListenerSpec.kt#L30

**Comment by jsalinaspolo** [comment]
Closing the issue, feel free to open with comments if needed 🙇
