### ISSUE TITLE
logcaputre migration guide from 1.2.2 to 1.3.x

### ISSUE THREAD

**Issue by vipinsingh211** [jsalinaspolo/logcapture#189]
Hi,

Is there a migration document to upgrade from 1.2.2 to 1.3.0 for instance? As I am seeing many unrelated tests failing once I update the version.

I am using:
```
kotlin("jvm") version "1.8.22"
io.kotest version 5.3.1
testImplementation("org.logcapture:logcapture-core:1.2.2")
testImplementation("org.logcapture:logcapture-kotest:1.2.2")
```

Thanks

**Comment by jsalinaspolo** [comment]
I am looking into it, as we are having similar issues with kotest.

**Comment by jsalinaspolo** [comment]
@vipinsingh211 I've identified that there are issues with `kotest` because version `5.7.x` have breaking changes.
I am looking for a workaround, but let me know if upgrading to latest `kotest` fix the issue 🙏

**Comment by vipinsingh211** [comment]
Thanks for the comment. Unfortunately, I can't upgrade above 5.3.1 at the moment as beyond this version there are breaking changes related to BehavoirSpec which will force me to do major refactoring.

**Comment by jsalinaspolo** [comment]
I will recommend to exclude `kotest` from the `logcapture` dependency with something like 

```testImplementation ("org.logcapture:logcapture-kotest:1.3.2") { exclude(group = "io.kotest") }```
